export const IS_LOADING = 'IS_LOADING'
export const IS_NOT_LOADING = 'IS_NOT_LOADING'

export const UPDATE_PROJECT_URL = 'UPDATE_PROJECT_URL'

export const SEARCH_VIEW = 'SEARCH_VIEW'
export const PALETTE_VIEW = 'PALETTE_VIEW'

export const COLOR_DETAIL = 'COLOR_DETAIL'
export const CLEAR_COLOR = 'CLEAR_COLOR'
