export const IS_LOADING = 'IS_LOADING';
export const IS_NOT_LOADING = 'IS_NOT_LOADING';

export const UPDATE_PROJECT_URL = 'UPDATE_PROJECT_URL';
export const UPDATE_PROJECT_NAME = 'UPDATE_PROJECT_NAME';
export const UPDATE_DEFAULT_BRANCH = 'UPDATE_DEFAULT_BRANCH';

export const UPDATE_FORM_FIELD = 'UPDATE_FORM_FIELD';
export const SHOW_INFO_FIELDS = 'SHOW_INFO_FIELDS';
export const SHOW_URL_FIELDS = 'SHOW_URL_FIELDS';

export const COLOR_DETAIL = 'COLOR_DETAIL';
export const CLEAR_COLOR = 'CLEAR_COLOR';

export const FETCH_PALETTE = 'FETCH_PALETTE';
export const SET_PALETTE = 'SET_PALETTE';

export const ERROR = 'ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';

export const UPDATE_FILTER_TEXT = 'UPDATE_FILTER_TEXT';

export const UPDATE_FILTER_SELECT = 'UPDATE_FILTER_SELECT';
export const ENABLE_FILTER_SELECT = 'ENABLE_FILTER_SELECT';
export const DISABLE_FILTER_SELECT = 'DISABLE_FILTER_SELECT';

export const UPDATE_SORT_SELECT = 'UPDATE_SORT_SELECT';
export const UPDATE_SORT_ORDER = 'UPDATE_SORT_ORDER';

export const CHANGE_PALETTE_VIEW = 'CHANGE_PALETTE_VIEW';
